// Generated by CoffeeScript 1.4.0
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use(express["static"](__dirname));

  app.listen(5000);

}).call(this);
